server:
  port: 8883
spring:
  application:
    name: transaction-services
  datasource:
    url: jdbc:mysql://mysql-db:3306/microbank
    username: hardik123
    password: hardik123
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8880/eureka